closes #9
mtswd/gl pull request #13
Opened 2021-02-19 15:32 UTC by Cereha

2021-02-19 16:38 UTC, tkroman requested changes
Please add your account name to CONTRIBUTORS
Please use proper naming for functions, i.e. if you want a `2:5` slice, an OK name would be `get_second_to_fifth_elements` or sth similar.

2021-02-20 08:21 UTC, tkroman requested changes

2021-02-20 08:21 UTC, tkroman commented on CONTRIBUTORS
> +cereha-koroban olya fi94
just github name

2021-02-22 18:02 UTC, YourFrieng commented on test_list.py
> +          def test_Olya_Koroban_FI94(self):
Delete excess spaces

2021-02-23 09:08 UTC, nogov approved these changes

2021-02-23 18:00 UTC, tkroman approved these changes

2021-02-23 18:01 UTC, merged