Update test_list.py
mtswd/gl pull request #53
Opened 2021-02-20 01:08 UTC by Dmytro-Mld

Added broken test

2021-02-20 01:20 UTC, Dmytro-Mld commented
Correct code

2021-02-20 08:20 UTC, tkroman requested changes

2021-02-20 08:20 UTC, tkroman commented on test_list.py
> +    def test_polina_kozarovitskaya(self):
why is this in your pr?

2021-02-20 08:20 UTC, tkroman commented on test_list.py
> +        def test_dmytro_moldovan_(self):
wrong indentation

2021-02-20 14:56 UTC, tkroman commented on CONTRIBUTORS
> +ikripaka
x2 (see line 5)

2021-02-21 09:23 UTC, nogov requested changes

2021-02-21 09:23 UTC, nogov commented on CONTRIBUTORS
> +ikripaka
PJeys mentioned twice, ikripaka was moved.
This file's diff should contain only the addition of your account name. Fix, please.

2021-02-21 09:37 UTC, nogov submitted a review, later dismissed

2021-02-21 13:47 UTC, tkroman approved these changes

2021-02-21 13:47 UTC, merged